---

- name: Create the fedora database
  mysql_db:
    name: "{{ fedora_db_name }}"
    state: present

- name: Create the fedora-commons user
  mysql_user:
    name: "{{ fedora_db_user }}"
    password: "{{ fedora_db_password }}"
    host: 192.168.10.0/255.255.255.0
    state: present
    priv: "fedora.*:ALL"

- name: Create the fedora-commons user
  mysql_user:
    name: "{{ fedora_db_user }}"
    password: "{{ fedora_db_password }}"
    host: localhost
    state: present
    priv: "fedora.*:ALL"
