---
#Install and start MariaDB
- include: apt_package.yml
  when: ansible_os_family == 'Debian'
- include: yum_package.yml
  when: ansible_os_family == 'RedHat'

#Root password
- name: Change the root password
  mysql_user: user="root"
              password="{{ mysql_root_password }}"
              host="localhost"

#Adding MariaDB configuration
- name: Create MariaDB configuration file Debian/Ubuntu
  template : src=myDebian.cnf.j2 dest=/etc/mysql/my.cnf
  notify: restart mysql
  when: ansible_os_family == 'Debian'

- name: Create MariaDB configuration file RedHat/CentOS
  template : src=myRedhat.cnf.j2 dest=/etc/my.cnf
  notify: restart mariadb
  when: ansible_os_family == 'RedHat'

- name: Copy .my.cnf to the root home directory
  copy: src=/etc/mysql/my.cnf dest=/root/.my.cnf
  when: ansible_os_family == 'Debian'

- name: Copy .my.cnf to the root home directory
  copy: src=/etc/my.cnf dest=/root/.my.cnf
  when: ansible_os_family == 'RedHat'

#Delete the useless code
- name: Delete the anonymous sql server user
  mysql_user: user=""
              state="absent"

- name: Delete the anonymous sql server user
  mysql_user: user=""
              host="erudit-vm-dev"
              state="absent"
  
- name: Remove the MariaDB test database
  mysql_db: name="test"
            state="absent"

#Fedora-Commons configuration
- include: fedora.yml
