---
#Install and start MariaDB
- include: apt_package.yml
  when: ansible_os_family == 'Debian'
- include: yum_package.yml
  when: ansible_os_family == 'RedHat'

#Adding MariaDB configuration
- name: Create MariaDB configuration file Debian/Ubuntu
  template : src=myDebian.cnf.j2 dest=/etc/mysql/my.cnf
  notify: restart mysql
  when: ansible_os_family == 'Debian'

- name: Create MariaDB configuration file RedHat/CentOS
  template : src=myRedhat.cnf.j2 dest=/etc/my.cnf
  notify: restart mariadb
  when: ansible_os_family == 'RedHat'
