---
#Task file for installing MariaDB on apt based distros

- name: Install MariaDB via yum
  yum: pkg={{ item }}
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

- name: Start MariaDB service
  service: name=mariadb state=started enabled=yes
