---
- name: Download Fedora-Commons source
  get_url: url=http://sourceforge.net/projects/fedora-commons/files/fedora/{{ fedora_version }}/fcrepo-installer-{{ fedora_version }}.jar dest=/vagrant/downloads/fcrepo-installer-{{ fedora_version }}.jar

- name: Create common folder in tomcat root
  file: path=/usr/share/tomcat/common state=directory

- name: Add adobe repo
  yum: name=http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm state=present

- name: Install flash-plugin package
  yum : name=flash-plugin state=present

- name: Create symbolic link
  file: src=/usr/share/tomcat/lib path=/usr/share/tomcat/common/lib state=link

- name: Download mysql-connection-java
  get_url: url=http://mirrors.ibiblio.org/pub/mirrors/maven2/mysql/mysql-connector-java/5.1.6/mysql-connector-java-5.1.6.jar dest=/usr/share/tomcat/lib/mysql-connector-java-5.1.6.jar 

- name: Copy install.properties
  template: src=/vagrant/ansible/roles/fedora/templates/install.properties.j2 dest=/tmp/install.properties

- name: Install Fedora-Commons
  command: /usr/bin/java -jar /vagrant/downloads/fcrepo-installer-{{ fedora_version }}.jar /tmp/install.properties creates=/var/lib/tomcat/fedora
  
- name: Wait until the webapps are installed
  wait_for: path=/var/lib/tomcat/webapps/fedora/WEB-INF

- name: Copy web.xml in the fedora-commons folder
  copy: src=/vagrant/ansible/roles/fedora/files/web.xml dest=/var/lib/tomcat/webapps/fedora/WEB-INF/web.xml
  notify: 
    - change fedora ownership
    - change tomcat ownership redhat
    - restart tomcat
