---
- name: restart tomcat
  service:
    name: tomcat
    state: restarted
    enabled: yes

- name: change tomcat ownership
  file:
    path: "{{ tomcat_home }}"
    owner: tomcat
    group: tomcat
    state: directory
    recurse: yes
