---
- name: restart tomcat
  service: name=tomcat state=restarted
- name: restart tomcat7
  service: name=tomcat7 state=restarted

- name: change ownership redhat
  file: path=/usr/share/tomcat owner=tomcat group=tomcat state=directory recurse=yes
  when: ansible_os_family == 'RedHat'

- name: change ownership debian
  file: path=/etc/tomcat7 owner=tomcat group=tomcat state=directory recurse=yes
  when: ansible_os_family == 'Debian'
