---
- name: Create download directory
  file: path=/home/vagrant/sync/downloads/ state=directory

- name: Install useful package
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - vim
    - bash-completion
    - tcpdump
    - git
    - sudo
    - python-keyczar
    - unzip
    - htop
    - wget

- name: Stop firewalld service
  service:
    name: firewalld
    state: stopped

- name: Add repository
  yum:
    name: http://www.city-fan.org/ftp/contrib/yum-repo/city-fan.org-release-1-13.rhel6.noarch.rpm
    state: present

- name: Install latest libcurl package
  yum:
    name: libcurl
    state: latest
    update_cache: yes
