---
- name: Create download directory
  file: path=/home/vagrant/sync/downloads/ state=directory

- name: Install useful package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - bash-completion
    - tcpdump
    - git
    - sudo
    - python-keyczar
    - unzip
    - htop
    - wget
    - tmux
    - nss
    - libcurl

- name: Stop firewalld service
  service:
    name: firewalld
    state: stopped

- name: Copy gitlab certificate
  copy:
    src: gitlab.erudit.team.crt
    dest: /etc/pki/ca-trust/source/anchors/gitlab.erudit.team.crt
    owner: root
    group: root
  notify:
    - update certificate
