---
- name: Install Apache, MariaDB, Tomcat, Fedora-Commons, Solr
  hosts: vm-dev
  remote_user: vagrant
  sudo: yes

  roles:
    - mariadb
    - tomcat
    - apache
    - { role: fedora, tomcat_http_port: 8080, tomcat_https_port: 8443 }
