---
- name: Downloading SOLR
  get_url:
    url: "{{ solr_url }}"
    dest: /home/vagrant/sync/downloads/solr-{{ solr_version }}.tgz
    checksum: "sha1:{{ solr_sha1sum }}"

- name: Extracting SOLR
  unarchive:
    src: /home/vagrant/sync/downloads/solr-{{ solr_version }}.tgz
    dest: /tmp
    creates: yes

- name: Installing the SOLR webapps
  copy:
    src: /tmp/solr-{{ solr_version }}/dist/solr-{{ solr_version }}.war
    dest: "{{ tomcat_home }}/webapps/solr.war"
    owner: tomcat
    group: tomcat

- name: Downloading commons-logging
  get_url:
    url: http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.2/commons-logging-1.1.2.jar
    dest: "{{ tomcat_home }}/lib/"
    checksum: "sha1:3b2888239ebec822dff8ed7ebf96293302e4b23b"

- name: Copy log4j libs in the Tomcat folder
  copy:
    src: /tmp/solr-{{ solr_version }}/example/lib/ext/log4j-1.2.17.jar
    dest: "{{ tomcat_home }}/lib/log4j-1.2.17.jar"

- name: stat SOLR folder
  stat:
    path: "{{ solr_home }}"
  register: solr_stat
  always_run: true

- name: Installing SOLR
  command: cp -r /tmp/solr-{{ solr_version }}/example/solr {{ solr_home }}
  when: solr_stat.stat.exists == false

- name: Copying the schema.xml template
  template:
    src: /home/vagrant/sync/ansible/roles/solr/templates/schema.xml.j2
    dest: "{{ solr_home }}/collection1/conf/schema.xml"
  notify:
    - change ownership solr

- name: Copying the solr.xml template
  template:
    src: /home/vagrant/sync/ansible/roles/solr/templates/solr.xml.j2
    dest: "{{ tomcat_home }}/conf/Catalina/localhost/solr.xml"
  notify:
    - restart tomcat

- name: Copy contrib folder in solr home
  copy:
    src: /tmp/solr-{{ solr_version }}/contrib
    dest: "{{ solr_home }}/contrib"
    owner: tomcat
    group: tomcat

- name: Copy dist folder in solr home
  copy:
    src: /tmp/solr-{{ solr_version }}/dist
    dest: "{{ solr_home }}/dist"
    owner: tomcat
    group: tomcat

- meta: flush_handlers

- name: Wait for WEB-INF/lib folder
  wait_for:
    path: "{{ tomcat_home }}/webapps/solr/WEB-INF/lib"

- name: Copy slf4j libs in the Tomcat folder
  copy:
    src: /tmp/solr-{{ solr_version }}/example/lib/ext/{{ item }}
    dest: "{{ tomcat_home }}/webapps/solr/WEB-INF/lib/{{ item }}"
  with_items:
    - slf4j-api-1.7.6.jar
    - slf4j-log4j12-1.7.6.jar
  notify:
    - change ownership solr
    - restart tomcat
