---
- name: Downloading SOLR
  get_url:
    url: "{{ solr_url }}"
    dest: "{{ solr_download }}/"
    checksum: "sha1:{{ solr_sha1sum }}"

- name: Extracting SOLR
  unarchive:
    src: "{{ solr_download }}/solr-{{ solr_version }}.tgz"
    dest: "{{ solr_download }}"
    creates: "{{ solr_extracted_war }}"

- name: Installing the SOLR webapps
  copy:
    src: "{{ solr_extracted_war }}"
    dest: "{{ tomcat_home }}/webapps/solr.war"
    owner: tomcat
    group: tomcat

- name: Downloading commons-logging
  get_url:
    url: http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.2/commons-logging-1.1.2.jar
    dest: "{{ tomcat_home }}/lib/"
    checksum: "sha1:3b2888239ebec822dff8ed7ebf96293302e4b23b"

- name: Copy log4j libs in the Tomcat folder
  copy:
    src: "{{ solr_log4j_jar }}"
    dest: "{{ tomcat_home }}/lib/log4j-1.2.17.jar"

- name: stat SOLR folder
  stat:
    path: "{{ solr_home }}"
  register: solr_stat
  always_run: true

- name: Installing SOLR
  synchronize:
    src: "{{ item }}"
    dest: "{{ solr_home }}/"
  with_items:
    - "{{ solr_home_src }}/"
    - "{{ solr_contrib_src }}"
    - "{{ solr_dist_src }}"
  when: solr_stat.stat.exists == false
  delegate_to: "{{ inventory_hostname }}"

- name: Copying the schema.xml template
  template:
    src: schema.xml.j2
    dest: "{{ solr_home }}/collection1/conf/schema.xml"
    owner: tomcat
    group: tomcat

- name: Copying the solr.xml template
  template:
    src: solr.xml.j2
    dest: "{{ tomcat_home }}/conf/Catalina/localhost/solr.xml"
  notify:
    - restart tomcat

- meta: flush_handlers

- name: Wait for WEB-INF/lib folder
  wait_for:
    path: "{{ tomcat_home }}/webapps/solr/WEB-INF/lib"

- name: Copy slf4j libs in the Tomcat folder
  copy:
    src: "{{ solr_slf4j_src }}/{{ item }}"
    dest: "{{ tomcat_home }}/webapps/solr/WEB-INF/lib/{{ item }}"
  with_items:
    - slf4j-api-1.7.6.jar
    - slf4j-log4j12-1.7.6.jar
  notify:
    - restart tomcat

- name: change ownership solr
  file:
    path: "{{ solr_home }}" 
    owner: tomcat
    group: tomcat
    state: directory
    recurse: yes
